name: cidaas_flutter_sdk
description: cidaas sdk for flutter
version: 1.0.0-dev.1
homepage: https://www.cidaas.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  http: ^0.12.0+4
  flutter_secure_storage: ^3.3.3
  flutter_webview_plugin: ^0.3.10+2
  provider: ^4.0.4
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/